// actionType.js

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const QUESTION_FAILURE = 'QUESTION_FAILURE';
export const QUESTION_REQUIRE = 'QUESTION_REQUIRE';
export const DELETE_QUESTION_SUCCESS="DELETE_QUESTION_SUCCESS"
